services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: summapp
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - smp

  redis:
    image: redis:8.0-alpine
    container_name: summapp-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - smp

  summapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: summapp
    depends_on:
      - mysql
      - redis
    ports:
      - '8080:8080'
    networks:
      - smp



networks:
  smp:
    driver: bridge

volumes:
  db:
    driver: local
  redis-data:
    driver: local