services:
  mysql:
    container_name: mysql-smp
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: summapp
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - smp


networks:
  smp:
    driver: bridge

volumes:
  db:
    driver: local